apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: upbound-default
  namespace: upbound-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-secret
      key: creds