apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: crossplane
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.11.1
    helm:
      releaseName: crossplane
      # parameters:
      #   - name: replicas
      #     value: "1"
      values: |
        replicas: 3
    syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  destination:
    server: "https://10.0.0.115:6443"
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true