apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contrib-provider-aws
  namespace: argocd
spec:
  project: crossplane
  source:
    repoURL: 'git@github.com:aatchison/argocd-crossplane.git'
    path: crossplane/providers/crossplane-contrib
    targetRevision: HEAD
  destination:
    server: 'https://10.0.0.115:6443'
    namespace: crossplane-system
  syncPolicy:
    automated: 
       prune: true