apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: control-plane
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: This is just an example.
  destinations:
    - name: crossplane
      namespace: crossplane-system
      server: 'https://10.0.0.115:6443'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/aatchison/argocd-crossplane'
    - 'https://charts.crossplane.io/stable'
status: {}